screen_addict_homepage:
    path:     /
    defaults: { _controller: screenAddictBundle:Default:index }

login_check:
    path: /login_check

logout:
    path: /logout

home:
    path: /home
    defaults: { _controller: screenAddictBundle:Default:login }

rechercher:
    path: /home/rechercher
    defaults: { _controller: screenAddictBundle:Default:rechercher }
    methods: [post]
